"""add_end_date_to_cohort

Revision ID: 06f17cef8ede
Revises: d7b2bdc37f8f
Create Date: 2026-03-03 12:05:34.341773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f17cef8ede'
down_revision = 'd7b2bdc37f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cohorts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cohorts', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
