"""add_notifications_and_joined_at

Revision ID: f43ac6116424
Revises: 9c644fa97af2
Create Date: 2026-03-02 23:13:58.417553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43ac6116424'
down_revision = '9c644fa97af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_column('joined_at')

    # ### end Alembic commands ###
